version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: resume_matcher
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"



  tika:
    image: apache/tika:2.9.2.1
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    ports:
      - "9998:9998"

  presidio-analyzer:
    image: mcr.microsoft.com/presidio-analyzer:latest
    platform: linux/amd64
    environment:
      - ANALYZER_LOG_LEVEL=INFO
    ports:
      - "3000:3000"

  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    platform: linux/amd64
    environment:
      - ANONYMIZER_LOG_LEVEL=INFO
    ports:
      - "3001:3000"

  latex:
    image: texlive/texlive:latest-full
    container_name: latex
    volumes:
      - ./latex:/latex
    working_dir: /latex
    command: ["tail", "-f", "/dev/null"]
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:

